import React, { useState } from 'react';
import {
  AlertCircle,
  Clock,
  Edit,
  MessageCircle,
  FileText,
  Trash2,
  ChevronDown,
  ChevronUp,
  CheckCircle2,
  Info,
  Image as ImageIcon
} from 'lucide-react';

const SubscriberCard = ({
  subscriber,
  onPay,
  onHistory,
  onOpenChat,
  onViewReceipt,
  onEdit,
  onDelete,
  userRole,
  onRefresh
}) => {
  const [showDetails, setShowDetails] = useState(false);

  const handleSendReminder = () => {
    const amount = subscriber.status === 'Partial' ? subscriber.remainingBalance : subscriber.amountDue;
    const message = `Hi ${subscriber.name}, your bill for ${subscriber.currentMonthName || 'this month'} is ${subscriber.status}. Total Due: ₱${amount.toLocaleString()} (after ₱${subscriber.rebate.toLocaleString()} rebate). Thank you!`;

    if (subscriber.messengerId) {
      const url = `https://m.me/${subscriber.messengerId}?text=${encodeURIComponent(message)}`;
      window.open(url, '_blank');
    } else {
      if (subscriber.contactNo) {
        const smsUrl = `sms:${subscriber.contactNo}?body=${encodeURIComponent(message)}`;
        window.open(smsUrl, '_blank');
      } else {
        const url = `https://m.me/?text=${encodeURIComponent(message)}`;
        window.open(url, '_blank');
      }
    }
  };

  const handleDownloadSOA = () => {
    const amount = subscriber.status === 'Partial' ? subscriber.remainingBalance : subscriber.amountDue;
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>SOA - ${subscriber.name}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #334155; }
            .header { border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 30px; }
            .row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #f1f5f9; }
            .total { font-size: 24px; font-weight: bold; color: #4f46e5; margin-top: 30px; }
            .footer { margin-top: 50px; font-size: 12px; color: #94a3b8; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Statement of Account</h1>
            <p>Subscriber: <strong>${subscriber.name}</strong></p>
            <p>Billing Period: ${subscriber.currentMonthName || 'Current Month'}</p>
          </div>
          <div class="row"><span>Monthly Rate</span><span>₱${subscriber.rate.toLocaleString()}</span></div>
          <div class="row"><span>Outage Rebate (${subscriber.daysDown} days)</span><span>-₱${subscriber.rebate.toLocaleString()}</span></div>
          <div class="row"><span>Total Amount for Period</span><span>₱${subscriber.amountDue.toLocaleString()}</span></div>
          <div class="row"><span>Payments Made</span><span>₱${(subscriber.amountDue - (subscriber.status === 'Partial' ? subscriber.remainingBalance : (subscriber.status === 'Paid' ? 0 : subscriber.amountDue))).toLocaleString()}</span></div>
          <div class="total flex justify-between"><span>Remaining Balance</span><span>₱${(subscriber.status === 'Paid' ? 0 : amount).toLocaleString()}</span></div>
          <div class="footer">Generated by BayadNet Pro on ${new Date().toLocaleDateString()}</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.document.addEventListener('load', () => {
      printWindow.print();
    }, true);
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'Paid': return 'bg-emerald-500/10 text-emerald-600 border-emerald-500/20';
      case 'Overdue': return 'bg-rose-500/10 text-rose-600 border-rose-500/20';
      case 'Due Today': return 'bg-orange-500/10 text-orange-600 border-orange-500/20';
      case 'Partial': return 'bg-amber-500/10 text-amber-600 border-amber-500/20';
      default: return 'bg-slate-500/10 text-slate-600 border-slate-500/20';
    }
  };

  const isPaid = subscriber.status === 'Paid';
  const hasActiveIssues = subscriber.reports && subscriber.reports.length > 0;
  const unreadCount = subscriber.reports ? subscriber.reports.filter(r => !r.readBy || r.readBy.length <= 1).length : 0;

  return (
    <div className="bg-white rounded-[3rem] shadow-xl shadow-slate-200/50 border border-slate-100 p-8 flex flex-col gap-6 hover:shadow-2xl hover:shadow-indigo-100/40 transition-all duration-500 group relative overflow-hidden">
      {/* Top Section: Name and Status */}
      <div className="flex justify-between items-start">
        <div className="max-w-[70%]">
          <h3 className="font-black text-2xl text-slate-900 truncate tracking-tight group-hover:text-indigo-600 transition-colors">
            {subscriber.name}
          </h3>
          <p className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] mt-1">
            Cycle: {subscriber.cycle}th
          </p>
        </div>
        <div className="flex flex-col items-end gap-2">
          {hasActiveIssues && (
            <div className="flex items-center gap-1 bg-amber-50 text-amber-600 px-2 py-1 rounded-full animate-pulse border border-amber-100">
              <AlertCircle className="w-3 h-3" />
              <span className="text-[8px] font-black uppercase tracking-tighter">{subscriber.reports.length} Issues</span>
            </div>
          )}
          <span className={`px-3 py-1.5 rounded-full text-[9px] font-black uppercase tracking-widest border ${getStatusColor(subscriber.status)} shadow-sm`}>
            {subscriber.status}
          </span>
        </div>
      </div>

      {/* Main Stats Card */}
      <div className="bg-slate-50/50 rounded-[2.5rem] p-6 border border-slate-100 space-y-4">
        {showDetails && (
          <div className="space-y-3 pb-4 border-b border-dashed border-slate-200 animate-in slide-in-from-top-2 duration-300">
            <div className="flex justify-between items-center text-[10px] font-bold uppercase tracking-wider">
              <span className="text-slate-400">Monthly Rate</span>
              <span className="text-slate-700 font-black">₱{subscriber.rate.toLocaleString()}</span>
            </div>
            {subscriber.daysDown > 0 && (
              <div className="flex justify-between items-center text-[10px] font-bold uppercase tracking-wider text-rose-500">
                <span>Outage ({subscriber.daysDown}d)</span>
                <span className="font-black">-₱{subscriber.rebate.toLocaleString()}</span>
              </div>
            )}
          </div>
        )}

        <div className="flex justify-between items-center">
          <div>
            <p className="text-[10px] text-slate-400 font-black uppercase tracking-widest mb-1">
              {subscriber.status === 'Partial' ? 'Balance' : 'Total Due'}
            </p>
            <p className="text-3xl font-black text-indigo-600 leading-none">
              ₱{(subscriber.status === 'Partial' ? subscriber.remainingBalance : subscriber.amountDue).toLocaleString()}
            </p>
          </div>
          <button
            onClick={() => setShowDetails(!showDetails)}
            className="p-2 bg-white rounded-full border border-slate-200 text-slate-400 hover:text-indigo-600 hover:border-indigo-100 transition-all shadow-sm"
          >
            {showDetails ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
          </button>
        </div>
      </div>

      {/* Date and Issues Summary */}
      <div className="grid grid-cols-2 gap-4">
        <div className="bg-white border border-slate-100 p-4 rounded-3xl shadow-sm">
          <p className="text-[9px] text-slate-400 font-black uppercase tracking-widest mb-1">Next Due</p>
          <p className="text-sm font-black text-slate-700 tracking-tight">{subscriber.dueDate}</p>
        </div>
        <button
          onClick={() => onOpenChat(subscriber)}
          className={`p-4 rounded-3xl border transition-all flex flex-col justify-center items-center shadow-sm ${
            unreadCount > 0
              ? 'bg-amber-50 border-amber-200 text-amber-600'
              : 'bg-white border-slate-100 text-slate-400 hover:bg-slate-50'
          }`}
        >
          <div className="flex items-center gap-2">
            <MessageCircle className="w-4 h-4" />
            <span className="text-sm font-black">{subscriber.reports?.length || 0}</span>
          </div>
          <p className="text-[8px] font-black uppercase tracking-widest">Issues</p>
        </button>
      </div>

      {/* Action Button */}
      {!isPaid ? (
        (userRole === 'admin' || userRole === 'staff') && (
          <button
            onClick={() => onPay(subscriber)}
            className="w-full bg-indigo-600 text-white text-[11px] font-black py-5 rounded-2xl hover:bg-indigo-700 hover:scale-[1.02] active:scale-95 transition-all shadow-xl shadow-indigo-100 uppercase tracking-[0.2em]"
          >
            {subscriber.status === 'Partial' ? 'Pay Balance' : 'Confirm Payment'}
          </button>
        )
      ) : (
        <div className="w-full bg-emerald-50 text-emerald-600 text-[10px] font-black py-5 rounded-2xl text-center border border-emerald-100 uppercase tracking-widest shadow-inner flex items-center justify-center gap-2">
          <CheckCircle2 className="w-4 h-4" />
          Account Settled
        </div>
      )}

      {/* Bottom Icon Bar */}
      <div className="flex items-center justify-between gap-2 px-1">
        <button
          onClick={() => onHistory(subscriber)}
          className="flex-1 aspect-square bg-white text-slate-400 rounded-2xl hover:bg-indigo-50 hover:text-indigo-600 hover:scale-110 active:scale-95 transition-all border border-slate-100 shadow-sm flex items-center justify-center"
          title="Payment History"
        >
          <Clock className="w-5 h-5" />
        </button>

        {userRole === 'admin' && (
          <button
            onClick={() => onEdit(subscriber)}
            className="flex-1 aspect-square bg-white text-slate-400 rounded-2xl hover:bg-indigo-50 hover:text-indigo-600 hover:scale-110 active:scale-95 transition-all border border-slate-100 shadow-sm flex items-center justify-center"
            title="Edit Subscriber"
          >
            <Edit className="w-5 h-5" />
          </button>
        )}

        <button
          onClick={() => onOpenChat(subscriber)}
          className="flex-1 aspect-square bg-white text-slate-400 rounded-2xl hover:bg-indigo-50 hover:text-indigo-600 hover:scale-110 active:scale-95 transition-all border border-slate-100 shadow-sm flex items-center justify-center relative"
          title="Issue Reports"
        >
          <MessageCircle className="w-5 h-5" />
          {unreadCount > 0 && (
            <span className="absolute top-2 right-2 w-2 h-2 bg-rose-500 rounded-full border-2 border-white"></span>
          )}
        </button>

        {(userRole === 'admin' || userRole === 'staff') && (
          <button
            onClick={handleDownloadSOA}
            className="flex-1 aspect-square bg-white text-slate-400 rounded-2xl hover:bg-indigo-50 hover:text-indigo-600 hover:scale-110 active:scale-95 transition-all border border-slate-100 shadow-sm flex items-center justify-center"
            title="Download SOA"
          >
            <FileText className="w-5 h-5" />
          </button>
        )}

        {subscriber.hasReceipt && (
          <button
            onClick={() => {
              const latestReceipt = subscriber.payments
                .filter(p => p.month === (subscriber.currentMonthName || 'February 2026') && p.receiptImage)
                .pop();
              if (latestReceipt) onViewReceipt(latestReceipt.receiptImage);
            }}
            className="flex-1 aspect-square bg-white text-emerald-500 rounded-2xl hover:bg-emerald-50 hover:scale-110 active:scale-95 transition-all border border-emerald-100 shadow-sm flex items-center justify-center"
            title="View Latest Receipt"
          >
            <ImageIcon className="w-5 h-5" />
          </button>
        )}

        {userRole === 'admin' && (
          <button
            onClick={() => onDelete(subscriber._id)}
            className="flex-1 aspect-square bg-white text-slate-400 rounded-2xl hover:bg-rose-50 hover:text-rose-600 hover:scale-110 active:scale-95 transition-all border border-slate-100 shadow-sm flex items-center justify-center"
            title="Archive Account"
          >
            <Trash2 className="w-5 h-5" />
          </button>
        )}
      </div>
    </div>
  );
};

export default SubscriberCard;
