import React from 'react';
import {
  Clock,
  Edit,
  MessageCircle,
  FileText,
  Trash2,
  CheckCircle2,
  Image as ImageIcon,
  AlertCircle
} from 'lucide-react';

const SubscriberCard = ({
  subscriber,
  onPay,
  onHistory,
  onOpenChat,
  onViewReceipt,
  onEdit,
  onDelete,
  onViewDetails,
  userRole
}) => {
  const handleDownloadSOA = (e) => {
    e.stopPropagation();
    const amount = subscriber.status === 'Partial' ? subscriber.remainingBalance : subscriber.amountDue;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const content = `
      <html>
        <head>
          <title>SOA - ${subscriber.name}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #111827; }
            .header { border-bottom: 2px solid #e5e7eb; padding-bottom: 20px; margin-bottom: 30px; }
            .row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #f3f4f6; }
            .total { font-size: 24px; font-weight: bold; color: #4f46e5; margin-top: 30px; }
            .footer { margin-top: 50px; font-size: 12px; color: #6b7280; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Statement of Account</h1>
            <p>Subscriber: <strong>${subscriber.name}</strong></p>
            <p>Billing Period: ${subscriber.currentMonthName || 'Current Month'}</p>
          </div>
          <div class="row"><span>Monthly Rate</span><span>₱${subscriber.rate.toLocaleString()}</span></div>
          <div class="row"><span>Outage Rebate (${subscriber.daysDown} days)</span><span>-₱${subscriber.rebate.toLocaleString()}</span></div>
          <div class="row"><span>Total Amount for Period</span><span>₱${subscriber.amountDue.toLocaleString()}</span></div>
          <div class="row"><span>Payments Made</span><span>₱${(subscriber.amountDue - (subscriber.status === 'Partial' ? subscriber.remainingBalance : (subscriber.status === 'Paid' ? 0 : subscriber.amountDue))).toLocaleString()}</span></div>
          <div class="total flex justify-between"><span>Remaining Balance</span><span>₱${(subscriber.status === 'Paid' ? 0 : amount).toLocaleString()}</span></div>
          <div class="footer">Generated by BayadNet Pro on ${new Date().toLocaleDateString()}</div>
        </body>
      </html>
    `;

    printWindow.document.write(content);
    printWindow.document.close();

    const checkReady = setInterval(() => {
      if (printWindow.document.readyState === 'complete') {
        clearInterval(checkReady);
        printWindow.print();
      }
    }, 100);
  };

  const getStatusStyle = (status) => {
    switch (status) {
      case 'Paid': return 'bg-emerald-50 text-emerald-700 border-emerald-100';
      case 'Overdue': return 'bg-red-50 text-red-700 border-red-100';
      case 'Due Today': return 'bg-orange-50 text-orange-700 border-orange-100';
      case 'Partial': return 'bg-amber-50 text-amber-700 border-amber-100';
      default: return 'bg-gray-50 text-gray-700 border-gray-200';
    }
  };

  const isPaid = subscriber.status === 'Paid';
  const unreadCount = subscriber.reports ? subscriber.reports.filter(r => !r.readBy || r.readBy.length <= 1).length : 0;
  const amount = subscriber.status === 'Partial' ? subscriber.remainingBalance : (isPaid ? 0 : subscriber.amountDue);
  const hasActiveIssue = subscriber.issueStatus === 'Open';

  return (
    <div className="bg-white rounded-lg border border-gray-200 p-3 flex items-center justify-between gap-4 hover:shadow-md hover:border-indigo-300 transition-all duration-200 group">
      {/* Left: Name & Info - Clickable for details */}
      <div
        className="flex-1 min-w-0 cursor-pointer"
        onClick={() => onViewDetails && onViewDetails(subscriber)}
      >
        <div className="flex items-center gap-2 mb-1">
          <h3 className="font-bold text-gray-900 truncate text-sm group-hover:text-indigo-600 transition-colors">
            {subscriber.name}
          </h3>
          <span className="text-[10px] font-semibold text-gray-400 uppercase tracking-wide bg-gray-50 px-1.5 py-0.5 rounded border border-gray-100">
            C{subscriber.cycle}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wide border ${getStatusStyle(subscriber.status)}`}>
            {subscriber.status}
          </span>
          {hasActiveIssue && (
            <div className="animate-pulse" title="Active Issue / Unresolved">
              <AlertCircle className="w-6 h-6 text-red-600 fill-red-100" strokeWidth={2.5} />
            </div>
          )}
        </div>
      </div>

      {/* Middle: Amount - Clickable for details */}
      <div
        className="text-right min-w-[90px] px-3 border-l border-gray-100 cursor-pointer"
        onClick={() => onViewDetails && onViewDetails(subscriber)}
      >
        <p className="text-[10px] text-gray-500 font-bold uppercase tracking-wide mb-0.5">Total Due</p>
        <p className={`text-sm font-bold ${isPaid ? 'text-emerald-600' : 'text-indigo-600'}`}>
          ₱{amount.toLocaleString()}
        </p>
      </div>

      {/* Right: Actions */}
      <div className="flex items-center gap-1.5 pl-1">
        <div className="flex items-center gap-1">
          <button
            onClick={(e) => { e.stopPropagation(); onHistory(subscriber); }}
            className="p-1.5 text-gray-400 hover:text-indigo-600 hover:bg-gray-50 rounded-md transition-all border border-transparent hover:border-gray-200"
            title="History"
          >
            <Clock className="w-4 h-4" />
          </button>

          {userRole === 'admin' && (
            <button
              onClick={(e) => { e.stopPropagation(); onEdit(subscriber); }}
              className="p-1.5 text-gray-400 hover:text-indigo-600 hover:bg-gray-50 rounded-md transition-all border border-transparent hover:border-gray-200"
              title="Edit"
            >
              <Edit className="w-4 h-4" />
            </button>
          )}

          <button
            onClick={(e) => { e.stopPropagation(); onOpenChat(subscriber); }}
            className={`p-1.5 rounded-md transition-all border border-transparent hover:border-gray-200 ${unreadCount > 0 || hasActiveIssue ? 'text-amber-600 bg-amber-50 border-amber-100' : 'text-gray-400 hover:text-indigo-600 hover:bg-gray-50'}`}
            title="Chat"
          >
            <MessageCircle className="w-4 h-4" />
          </button>

          {(userRole === 'admin' || userRole === 'staff') && (
            <>
              <button
                onClick={handleDownloadSOA}
                className="p-1.5 text-gray-400 hover:text-indigo-600 hover:bg-gray-50 rounded-md transition-all border border-transparent hover:border-gray-200"
                title="SOA"
              >
                <FileText className="w-4 h-4" />
              </button>
            </>
          )}

          {subscriber.hasReceipt && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                const latestReceipt = subscriber.payments
                  ?.filter(p => p.month === (subscriber.currentMonthName || 'February 2026') && p.receiptImage)
                  .pop();
                if (latestReceipt) onViewReceipt(latestReceipt.receiptImage);
              }}
              className="p-1.5 text-emerald-600 hover:bg-emerald-50 rounded-md transition-all border border-transparent hover:border-emerald-100"
              title="Receipt"
            >
              <ImageIcon className="w-4 h-4" />
            </button>
          )}

          {userRole === 'admin' && (
            <button
              onClick={(e) => { e.stopPropagation(); onDelete(subscriber._id); }}
              className="p-1.5 text-gray-300 hover:text-red-600 hover:bg-red-50 rounded-md transition-all border border-transparent hover:border-red-100"
              title="Archive"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          )}
        </div>

        {!isPaid ? (
          (userRole === 'admin' || userRole === 'staff') && (
            <button
              onClick={(e) => { e.stopPropagation(); onPay(subscriber); }}
              className="bg-indigo-600 text-white text-[10px] font-bold px-3 py-1.5 rounded-md hover:bg-indigo-700 shadow-sm active:scale-95 transition-all uppercase tracking-wide ml-1"
            >
              Pay
            </button>
          )
        ) : (
          <div className="bg-emerald-50 text-emerald-600 p-1.5 rounded-md border border-emerald-100 ml-1" title="Settled">
            <CheckCircle2 className="w-4 h-4" />
          </div>
        )}
      </div>
    </div>
  );
};

export default SubscriberCard;
